# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./the_twelve_days_of_christmas.c .
RUN gcc -O3 -o ./the_twelve_days_of_christmas ./the_twelve_days_of_christmas.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/the_twelve_days_of_christmas .
CMD ["./the_twelve_days_of_christmas"]
