# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./approximate_equality.c .
RUN gcc -O3 -o ./approximate_equality ./approximate_equality.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/approximate_equality .
CMD ["./approximate_equality"]
