# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./problem_of_apollonius.c .
RUN gcc -O3 -o ./problem_of_apollonius ./problem_of_apollonius.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/problem_of_apollonius .
CMD ["./problem_of_apollonius"]
