# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./evaluate_binomial_coefficients.c .
RUN gcc -O3 -o ./evaluate_binomial_coefficients ./evaluate_binomial_coefficients.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/evaluate_binomial_coefficients .
CMD ["./evaluate_binomial_coefficients"]
