# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./knuth_shuffle.c .
RUN gcc -O3 -o ./knuth_shuffle ./knuth_shuffle.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/knuth_shuffle .
CMD ["./knuth_shuffle"]
