# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./lucas-lehmer_test.c .
RUN gcc -O3 -o ./lucas-lehmer_test ./lucas-lehmer_test.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/lucas-lehmer_test .
CMD ["./lucas-lehmer_test"]
