# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./cheryls_birthday.c .
RUN gcc -O3 -o ./cheryls_birthday ./cheryls_birthday.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/cheryls_birthday .
CMD ["./cheryls_birthday"]
