# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./roman_numerals-encode.c .
RUN gcc -O3 -o ./roman_numerals-encode ./roman_numerals-encode.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/roman_numerals-encode .
CMD ["./roman_numerals-encode"]
