# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./parsing-rpn_calculator_algorithm.c .
RUN gcc -O3 -o ./parsing-rpn_calculator_algorithm ./parsing-rpn_calculator_algorithm.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/parsing-rpn_calculator_algorithm .
CMD ["./parsing-rpn_calculator_algorithm"]
