# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./faulhabers_triangle.c .
RUN gcc -O3 -o ./faulhabers_triangle ./faulhabers_triangle.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/faulhabers_triangle .
CMD ["./faulhabers_triangle"]
