# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./subtractive_generator.c .
RUN gcc -O3 -o ./subtractive_generator ./subtractive_generator.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/subtractive_generator .
CMD ["./subtractive_generator"]
