# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./greatest_subsequential_sum.c .
RUN gcc -O3 -o ./greatest_subsequential_sum ./greatest_subsequential_sum.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/greatest_subsequential_sum .
CMD ["./greatest_subsequential_sum"]
