# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./harshad_or_niven_series.c .
RUN gcc -O3 -o ./harshad_or_niven_series ./harshad_or_niven_series.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/harshad_or_niven_series .
CMD ["./harshad_or_niven_series"]
