# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./kolakoski_sequence.c .
RUN gcc -O3 -o ./kolakoski_sequence ./kolakoski_sequence.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/kolakoski_sequence .
CMD ["./kolakoski_sequence"]
