# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./negative_base_numbers.c .
RUN gcc -O3 -o ./negative_base_numbers ./negative_base_numbers.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/negative_base_numbers .
CMD ["./negative_base_numbers"]
