# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./p-value_correction.c .
RUN gcc -O3 -o ./p-value_correction ./p-value_correction.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/p-value_correction .
CMD ["./p-value_correction"]
