# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./show_the_epoch.c .
RUN gcc -O3 -o ./show_the_epoch ./show_the_epoch.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/show_the_epoch .
CMD ["./show_the_epoch"]
