# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./five_weekends.c .
RUN gcc -O3 -o ./five_weekends ./five_weekends.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/five_weekends .
CMD ["./five_weekends"]
