# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./stern-brocot_sequence.c .
RUN gcc -O3 -o ./stern-brocot_sequence ./stern-brocot_sequence.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/stern-brocot_sequence .
CMD ["./stern-brocot_sequence"]
