# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./trigonometric_functions.c .
RUN gcc -O3 -o ./trigonometric_functions ./trigonometric_functions.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/trigonometric_functions .
CMD ["./trigonometric_functions"]
