# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./averages-root_mean_square.c .
RUN gcc -O3 -o ./averages-root_mean_square ./averages-root_mean_square.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/averages-root_mean_square .
CMD ["./averages-root_mean_square"]
