# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./first-class_functions.c .
RUN gcc -O3 -o ./first-class_functions ./first-class_functions.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/first-class_functions .
CMD ["./first-class_functions"]
