# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./emirp_primes.c .
RUN gcc -O3 -o ./emirp_primes ./emirp_primes.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/emirp_primes .
CMD ["./emirp_primes"]
