# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./heronian_triangles.c .
RUN gcc -O3 -o ./heronian_triangles ./heronian_triangles.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/heronian_triangles .
CMD ["./heronian_triangles"]
