# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./balanced_brackets.c .
RUN gcc -O3 -o ./balanced_brackets ./balanced_brackets.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/balanced_brackets .
CMD ["./balanced_brackets"]
