# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./roots_of_unity.c .
RUN gcc -O3 -o ./roots_of_unity ./roots_of_unity.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/roots_of_unity .
CMD ["./roots_of_unity"]
