# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./named_parameters.c .
RUN gcc -O3 -o ./named_parameters ./named_parameters.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/named_parameters .
CMD ["./named_parameters"]
