# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./fast_fourier_transform.c .
RUN gcc -O3 -o ./fast_fourier_transform ./fast_fourier_transform.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/fast_fourier_transform .
CMD ["./fast_fourier_transform"]
