# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./sum_digits_of_an_integer.c .
RUN gcc -O3 -o ./sum_digits_of_an_integer ./sum_digits_of_an_integer.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/sum_digits_of_an_integer .
CMD ["./sum_digits_of_an_integer"]
