# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./taxicab_numbers.c .
RUN gcc -O3 -o ./taxicab_numbers ./taxicab_numbers.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/taxicab_numbers .
CMD ["./taxicab_numbers"]
