FROM clux/muslrust:stable as builder

WORKDIR /app

RUN USER=root cargo new time_wasi
WORKDIR /app/time_wasi

COPY Cargo.toml Cargo.lock ./

RUN echo 'fn main() { println!("Dummy") }' > ./src/main.rs

RUN cargo build --release

RUN rm -r target/x86_64-unknown-linux-musl/release/.fingerprint/time_wasi-*

COPY src src/
# COPY migrations migrations/
# COPY templates templates/

RUN cargo build --release --frozen --bin time_wasi


FROM alpine:latest

# COPY --from=builder /app/time_wasi/migrations /application/migrations
# COPY --from=builder /app/time_wasi/templates /application/templates
COPY --from=builder /app/time_wasi/target/x86_64-unknown-linux-musl/release/time_wasi /application/time_wasi

WORKDIR /application
CMD ["./time_wasi"]