# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./variable-length_quantity.c .
RUN gcc -O3 -o ./variable-length_quantity ./variable-length_quantity.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/variable-length_quantity .
CMD ["./variable-length_quantity"]
