# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./host_introspection.c .
RUN gcc -O3 -o ./host_introspection ./host_introspection.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/host_introspection .
CMD ["./host_introspection"]
