# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./sierpinski_triangle.c .
RUN gcc -O3 -o ./sierpinski_triangle ./sierpinski_triangle.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/sierpinski_triangle .
CMD ["./sierpinski_triangle"]
