# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./command-line_arguments.c .
RUN gcc -O3 -o ./command-line_arguments ./command-line_arguments.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/command-line_arguments .
CMD ["./command-line_arguments"]
