# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./deconvolution-1d.c .
RUN gcc -O3 -o ./deconvolution-1d ./deconvolution-1d.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/deconvolution-1d .
CMD ["./deconvolution-1d"]
