# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./start_from_a_main_routine.c .
RUN gcc -O3 -o ./start_from_a_main_routine ./start_from_a_main_routine.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/start_from_a_main_routine .
CMD ["./start_from_a_main_routine"]
