# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./determinant_and_permanent.c .
RUN gcc -O3 -o ./determinant_and_permanent ./determinant_and_permanent.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/determinant_and_permanent .
CMD ["./determinant_and_permanent"]
