# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./range_extraction.c .
RUN gcc -O3 -o ./range_extraction ./range_extraction.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/range_extraction .
CMD ["./range_extraction"]
