# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./universal_turing_machine.c .
RUN gcc -O3 -o ./universal_turing_machine ./universal_turing_machine.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/universal_turing_machine .
CMD ["./universal_turing_machine"]
