# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./orbital_elements.c .
RUN gcc -O3 -o ./orbital_elements ./orbital_elements.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/orbital_elements .
CMD ["./orbital_elements"]
