# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./quickselect_algorithm.c .
RUN gcc -O3 -o ./quickselect_algorithm ./quickselect_algorithm.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/quickselect_algorithm .
CMD ["./quickselect_algorithm"]
