# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./natural_sorting.c .
RUN gcc -O3 -o ./natural_sorting ./natural_sorting.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/natural_sorting .
CMD ["./natural_sorting"]
