# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./ramseys_theorem.c .
RUN gcc -O3 -o ./ramseys_theorem ./ramseys_theorem.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/ramseys_theorem .
CMD ["./ramseys_theorem"]
