# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./priority_queue.c .
RUN gcc -O3 -o ./priority_queue ./priority_queue.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/priority_queue .
CMD ["./priority_queue"]
