# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./sequence_smallest_number_with_exactly_n_divisors.c .
RUN gcc -O3 -o ./sequence_smallest_number_with_exactly_n_divisors ./sequence_smallest_number_with_exactly_n_divisors.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/sequence_smallest_number_with_exactly_n_divisors .
CMD ["./sequence_smallest_number_with_exactly_n_divisors"]
