# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./truncatable_primes.c .
RUN gcc -O3 -o ./truncatable_primes ./truncatable_primes.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/truncatable_primes .
CMD ["./truncatable_primes"]
