# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./parsing-rpn_to_infix_conversion.c .
RUN gcc -O3 -o ./parsing-rpn_to_infix_conversion ./parsing-rpn_to_infix_conversion.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/parsing-rpn_to_infix_conversion .
CMD ["./parsing-rpn_to_infix_conversion"]
