# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./probabilistic_choice.c .
RUN gcc -O3 -o ./probabilistic_choice ./probabilistic_choice.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/probabilistic_choice .
CMD ["./probabilistic_choice"]
