# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./the_isaac_cipher.c .
RUN gcc -O3 -o ./the_isaac_cipher ./the_isaac_cipher.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/the_isaac_cipher .
CMD ["./the_isaac_cipher"]
