# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./non-decimal_radices-output.c .
RUN gcc -O3 -o ./non-decimal_radices-output ./non-decimal_radices-output.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/non-decimal_radices-output .
CMD ["./non-decimal_radices-output"]
