# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./matrix_chain_multiplication.c .
RUN gcc -O3 -o ./matrix_chain_multiplication ./matrix_chain_multiplication.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/matrix_chain_multiplication .
CMD ["./matrix_chain_multiplication"]
