# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./playing_cards.c .
RUN gcc -O3 -o ./playing_cards ./playing_cards.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/playing_cards .
CMD ["./playing_cards"]
