# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./draw_a_cuboid.c .
RUN gcc -O3 -o ./draw_a_cuboid ./draw_a_cuboid.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/draw_a_cuboid .
CMD ["./draw_a_cuboid"]
