# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./tree_traversal.c .
RUN gcc -O3 -o ./tree_traversal ./tree_traversal.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/tree_traversal .
CMD ["./tree_traversal"]
