# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./regular_expressions.c .
RUN gcc -O3 -o ./regular_expressions ./regular_expressions.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/regular_expressions .
CMD ["./regular_expressions"]
