# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./zeckendorf_number_representation.c .
RUN gcc -O3 -o ./zeckendorf_number_representation ./zeckendorf_number_representation.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/zeckendorf_number_representation .
CMD ["./zeckendorf_number_representation"]
