# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./deconvolution-2d.c .
RUN gcc -O3 -o ./deconvolution-2d ./deconvolution-2d.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/deconvolution-2d .
CMD ["./deconvolution-2d"]
