# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./stem-and-leaf_plot.c .
RUN gcc -O3 -o ./stem-and-leaf_plot ./stem-and-leaf_plot.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/stem-and-leaf_plot .
CMD ["./stem-and-leaf_plot"]
