# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./comma_quibbling.c .
RUN gcc -O3 -o ./comma_quibbling ./comma_quibbling.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/comma_quibbling .
CMD ["./comma_quibbling"]
