# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./phrase_reversals.c .
RUN gcc -O3 -o ./phrase_reversals ./phrase_reversals.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/phrase_reversals .
CMD ["./phrase_reversals"]
