# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./create_an_html_table.c .
RUN gcc -O3 -o ./create_an_html_table ./create_an_html_table.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/create_an_html_table .
CMD ["./create_an_html_table"]
