# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./thue-morse.c .
RUN gcc -O3 -o ./thue-morse ./thue-morse.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/thue-morse .
CMD ["./thue-morse"]
