# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./search_a_list.c .
RUN gcc -O3 -o ./search_a_list ./search_a_list.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/search_a_list .
CMD ["./search_a_list"]
