# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./circles_of_given_radius_through_two_points.c .
RUN gcc -O3 -o ./circles_of_given_radius_through_two_points ./circles_of_given_radius_through_two_points.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/circles_of_given_radius_through_two_points .
CMD ["./circles_of_given_radius_through_two_points"]
