# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./pangram_checker.c .
RUN gcc -O3 -o ./pangram_checker ./pangram_checker.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/pangram_checker .
CMD ["./pangram_checker"]
