# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./balanced_ternary.c .
RUN gcc -O3 -o ./balanced_ternary ./balanced_ternary.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/balanced_ternary .
CMD ["./balanced_ternary"]
