# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./magic_squares_of_singly_even_order.c .
RUN gcc -O3 -o ./magic_squares_of_singly_even_order ./magic_squares_of_singly_even_order.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/magic_squares_of_singly_even_order .
CMD ["./magic_squares_of_singly_even_order"]
