# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./visualize_a_tree.c .
RUN gcc -O3 -o ./visualize_a_tree ./visualize_a_tree.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/visualize_a_tree .
CMD ["./visualize_a_tree"]
