# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./fraction-norm.cc .
RUN g++ -O3 -o ./fraction-norm ./fraction-norm.cc -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/fraction-norm .
CMD ["./fraction-norm"]
