# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./smith_numbers.c .
RUN gcc -O3 -o ./smith_numbers ./smith_numbers.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/smith_numbers .
CMD ["./smith_numbers"]
