# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./non-continuous_subsequences.c .
RUN gcc -O3 -o ./non-continuous_subsequences ./non-continuous_subsequences.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/non-continuous_subsequences .
CMD ["./non-continuous_subsequences"]
