# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./jewels_and_stones.c .
RUN gcc -O3 -o ./jewels_and_stones ./jewels_and_stones.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/jewels_and_stones .
CMD ["./jewels_and_stones"]
