# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./josephus_problem.c .
RUN gcc -O3 -o ./josephus_problem ./josephus_problem.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/josephus_problem .
CMD ["./josephus_problem"]
