# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./loops-increment_loop_index_within_loop_body.c .
RUN gcc -O3 -o ./loops-increment_loop_index_within_loop_body ./loops-increment_loop_index_within_loop_body.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/loops-increment_loop_index_within_loop_body .
CMD ["./loops-increment_loop_index_within_loop_body"]
