# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./sparkline_in_unicode.c .
RUN gcc -O3 -o ./sparkline_in_unicode ./sparkline_in_unicode.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/sparkline_in_unicode .
CMD ["./sparkline_in_unicode"]
