# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./linear-memory-analysis.c .
RUN gcc -O3 -o ./linear-memory-analysis ./linear-memory-analysis.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/linear-memory-analysis .
CMD ["./linear-memory-analysis"]
