# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./abc_problem.c .
RUN gcc -O3 -o ./abc_problem ./abc_problem.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/abc_problem .
CMD ["./abc_problem"]
