# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./spiral_matrix.c .
RUN gcc -O3 -o ./spiral_matrix ./spiral_matrix.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/spiral_matrix .
CMD ["./spiral_matrix"]
