# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./exponentiation_order.c .
RUN gcc -O3 -o ./exponentiation_order ./exponentiation_order.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/exponentiation_order .
CMD ["./exponentiation_order"]
