# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./print_debugging_statement.c .
RUN gcc -O3 -o ./print_debugging_statement ./print_debugging_statement.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/print_debugging_statement .
CMD ["./print_debugging_statement"]
