# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./floyds_triangle.c .
RUN gcc -O3 -o ./floyds_triangle ./floyds_triangle.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/floyds_triangle .
CMD ["./floyds_triangle"]
