# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./ethiopian_multiplication.c .
RUN gcc -O3 -o ./ethiopian_multiplication ./ethiopian_multiplication.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/ethiopian_multiplication .
CMD ["./ethiopian_multiplication"]
