# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./integer_roots.c .
RUN gcc -O3 -o ./integer_roots ./integer_roots.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/integer_roots .
CMD ["./integer_roots"]
