# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./luhn_test_of_credit_card_numbers.c .
RUN gcc -O3 -o ./luhn_test_of_credit_card_numbers ./luhn_test_of_credit_card_numbers.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/luhn_test_of_credit_card_numbers .
CMD ["./luhn_test_of_credit_card_numbers"]
