# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./egyptian_division.c .
RUN gcc -O3 -o ./egyptian_division ./egyptian_division.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/egyptian_division .
CMD ["./egyptian_division"]
