# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./eulers_identity.c .
RUN gcc -O3 -o ./eulers_identity ./eulers_identity.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/eulers_identity .
CMD ["./eulers_identity"]
