FROM clux/muslrust:stable as builder

WORKDIR /app

RUN USER=root cargo new native
WORKDIR /app/native

COPY Cargo.toml Cargo.lock ./

RUN echo 'fn main() { println!("Dummy") }' > ./src/main.rs

RUN cargo build --release

RUN rm -r target/x86_64-unknown-linux-musl/release/.fingerprint/native-*

COPY src src/
# COPY migrations migrations/
# COPY templates templates/

RUN cargo build --release --frozen --bin native


FROM alpine:latest

# COPY --from=builder /app/native/migrations /application/migrations
# COPY --from=builder /app/native/templates /application/templates
COPY --from=builder /app/native/target/x86_64-unknown-linux-musl/release/native /application/native

WORKDIR /application
CMD ["./native"]

