# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./jensens_device.c .
RUN gcc -O3 -o ./jensens_device ./jensens_device.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/jensens_device .
CMD ["./jensens_device"]
