# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./qr_decomposition.c .
RUN gcc -O3 -o ./qr_decomposition ./qr_decomposition.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/qr_decomposition .
CMD ["./qr_decomposition"]
