# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache clang gfortran make musl-dev
WORKDIR /app
COPY . .
RUN gcc -O3 -I utilities -I linear-algebra/blas/gemm utilities/polybench.c linear-algebra/blas/gemm/gemm.c -DPOLYBENCH_TIME -o linear-algebra/blas/gemm/gemm -lm
RUN cp linear-algebra/blas/gemm/gemm /app

# Production stage
FROM alpine
COPY --from=build-stage /app/gemm /gemm
CMD ["/gemm"]
