# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./mutual_recursion.c .
RUN gcc -O3 -o ./mutual_recursion ./mutual_recursion.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/mutual_recursion .
CMD ["./mutual_recursion"]
