# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./imaginary_base_numbers.c .
RUN gcc -O3 -o ./imaginary_base_numbers ./imaginary_base_numbers.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/imaginary_base_numbers .
CMD ["./imaginary_base_numbers"]
