# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./pascal_matrix_generation.c .
RUN gcc -O3 -o ./pascal_matrix_generation ./pascal_matrix_generation.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/pascal_matrix_generation .
CMD ["./pascal_matrix_generation"]
