# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./middle_three_digits.c .
RUN gcc -O3 -o ./middle_three_digits ./middle_three_digits.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/middle_three_digits .
CMD ["./middle_three_digits"]
