# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./memory_allocation.c .
RUN gcc -O3 -o ./memory_allocation ./memory_allocation.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/memory_allocation .
CMD ["./memory_allocation"]
