# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./hilbert_curve.c .
RUN gcc -O3 -o ./hilbert_curve ./hilbert_curve.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/hilbert_curve .
CMD ["./hilbert_curve"]
