# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache clang gfortran make musl-dev
WORKDIR /app
COPY . .
RUN gcc -O3 -I utilities -I linear-algebra/solvers/gramschmidt utilities/polybench.c linear-algebra/solvers/gramschmidt/gramschmidt.c -DPOLYBENCH_TIME -o linear-algebra/solvers/gramschmidt/gramschmidt -lm
RUN cp linear-algebra/solvers/gramschmidt/gramschmidt /app

# Production stage
FROM alpine
COPY --from=build-stage /app/gramschmidt /gramschmidt
CMD ["/gramschmidt"]
