# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./exponentiation_operator.c .
RUN gcc -O3 -o ./exponentiation_operator ./exponentiation_operator.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/exponentiation_operator .
CMD ["./exponentiation_operator"]
