# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./check_input_device_is_a_terminal.c .
RUN gcc -O3 -o ./check_input_device_is_a_terminal ./check_input_device_is_a_terminal.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/check_input_device_is_a_terminal .
CMD ["./check_input_device_is_a_terminal"]
