# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./sum_to_100.c .
RUN gcc -O3 -o ./sum_to_100 ./sum_to_100.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/sum_to_100 .
CMD ["./sum_to_100"]
