# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./maze_generation.c .
RUN gcc -O3 -o ./maze_generation ./maze_generation.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/maze_generation .
CMD ["./maze_generation"]
