# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./test_integerness.c .
RUN gcc -O3 -o ./test_integerness ./test_integerness.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/test_integerness .
CMD ["./test_integerness"]
