# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./sort_disjoint_sublist.c .
RUN gcc -O3 -o ./sort_disjoint_sublist ./sort_disjoint_sublist.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/sort_disjoint_sublist .
CMD ["./sort_disjoint_sublist"]
