# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./terminal_control-inverse_video.c .
RUN gcc -O3 -o ./terminal_control-inverse_video ./terminal_control-inverse_video.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/terminal_control-inverse_video .
CMD ["./terminal_control-inverse_video"]
