# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./hofstadter_q_sequence.c .
RUN gcc -O3 -o ./hofstadter_q_sequence ./hofstadter_q_sequence.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/hofstadter_q_sequence .
CMD ["./hofstadter_q_sequence"]
