# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./knapsack_problem-0-1.c .
RUN gcc -O3 -o ./knapsack_problem-0-1 ./knapsack_problem-0-1.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/knapsack_problem-0-1 .
CMD ["./knapsack_problem-0-1"]
