# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./strip_whitespace_from_a_string-top_and_tail.c .
RUN gcc -O3 -o ./strip_whitespace_from_a_string-top_and_tail ./strip_whitespace_from_a_string-top_and_tail.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/strip_whitespace_from_a_string-top_and_tail .
CMD ["./strip_whitespace_from_a_string-top_and_tail"]
