# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./soundex.c .
RUN gcc -O3 -o ./soundex ./soundex.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/soundex .
CMD ["./soundex"]
