# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./top_rank_per_group.c .
RUN gcc -O3 -o ./top_rank_per_group ./top_rank_per_group.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/top_rank_per_group .
CMD ["./top_rank_per_group"]
