# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./lu_decomposition.c .
RUN gcc -O3 -o ./lu_decomposition ./lu_decomposition.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/lu_decomposition .
CMD ["./lu_decomposition"]
