# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./pascals_triangle-puzzle.c .
RUN gcc -O3 -o ./pascals_triangle-puzzle ./pascals_triangle-puzzle.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/pascals_triangle-puzzle .
CMD ["./pascals_triangle-puzzle"]
