# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./continued_fraction.c .
RUN gcc -O3 -o ./continued_fraction ./continued_fraction.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/continued_fraction .
CMD ["./continued_fraction"]
