# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./least_common_multiple.c .
RUN gcc -O3 -o ./least_common_multiple ./least_common_multiple.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/least_common_multiple .
CMD ["./least_common_multiple"]
