# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache clang gfortran make musl-dev
WORKDIR /app
COPY . .
RUN gcc -O3 -I utilities -I linear-algebra/blas/gesummv utilities/polybench.c linear-algebra/blas/gesummv/gesummv.c -DPOLYBENCH_TIME -o linear-algebra/blas/gesummv/gesummv -lm
RUN cp linear-algebra/blas/gesummv/gesummv /app

# Production stage
FROM alpine
COPY --from=build-stage /app/gesummv /gesummv
CMD ["/gesummv"]
