# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./chinese_zodiac.c .
RUN gcc -O3 -o ./chinese_zodiac ./chinese_zodiac.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/chinese_zodiac .
CMD ["./chinese_zodiac"]
