# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./iterated_digits_squaring.c .
RUN gcc -O3 -o ./iterated_digits_squaring ./iterated_digits_squaring.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/iterated_digits_squaring .
CMD ["./iterated_digits_squaring"]
