# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./dice_game_probabilities.c .
RUN gcc -O3 -o ./dice_game_probabilities ./dice_game_probabilities.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/dice_game_probabilities .
CMD ["./dice_game_probabilities"]
