# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./environment_variables.c .
RUN gcc -O3 -o ./environment_variables ./environment_variables.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/environment_variables .
CMD ["./environment_variables"]
