# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./averages-mean_angle.c .
RUN gcc -O3 -o ./averages-mean_angle ./averages-mean_angle.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/averages-mean_angle .
CMD ["./averages-mean_angle"]
