# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./inverted_index.c .
RUN gcc -O3 -o ./inverted_index ./inverted_index.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/inverted_index .
CMD ["./inverted_index"]
