# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./equilibrium_index.c .
RUN gcc -O3 -o ./equilibrium_index ./equilibrium_index.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/equilibrium_index .
CMD ["./equilibrium_index"]
