# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./parametric_polymorphism.c .
RUN gcc -O3 -o ./parametric_polymorphism ./parametric_polymorphism.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/parametric_polymorphism .
CMD ["./parametric_polymorphism"]
