# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./box_the_compass.c .
RUN gcc -O3 -o ./box_the_compass ./box_the_compass.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/box_the_compass .
CMD ["./box_the_compass"]
