# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./haversine_formula.c .
RUN gcc -O3 -o ./haversine_formula ./haversine_formula.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/haversine_formula .
CMD ["./haversine_formula"]
