# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./resistor_mesh.c .
RUN gcc -O3 -o ./resistor_mesh ./resistor_mesh.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/resistor_mesh .
CMD ["./resistor_mesh"]
