# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache clang gfortran make musl-dev
WORKDIR /app
COPY . .
RUN gcc -O3 -I utilities -I linear-algebra/solvers/lu utilities/polybench.c linear-algebra/solvers/lu/lu.c -DPOLYBENCH_TIME -o linear-algebra/solvers/lu/lu -lm
RUN cp linear-algebra/solvers/lu/lu /app

# Production stage
FROM alpine
COPY --from=build-stage /app/lu /lu
CMD ["/lu"]
