# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./shortest_common_supersequence.c .
RUN gcc -O3 -o ./shortest_common_supersequence ./shortest_common_supersequence.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/shortest_common_supersequence .
CMD ["./shortest_common_supersequence"]
