# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./case-sensitivity_of_identifiers.c .
RUN gcc -O3 -o ./case-sensitivity_of_identifiers ./case-sensitivity_of_identifiers.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/case-sensitivity_of_identifiers .
CMD ["./case-sensitivity_of_identifiers"]
