# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./general_fizzbuzz.c .
RUN gcc -O3 -o ./general_fizzbuzz ./general_fizzbuzz.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/general_fizzbuzz .
CMD ["./general_fizzbuzz"]
