# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./accumulator_factory.c .
RUN gcc -O3 -o ./accumulator_factory ./accumulator_factory.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/accumulator_factory .
CMD ["./accumulator_factory"]
