# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./cramers_rule.c .
RUN gcc -O3 -o ./cramers_rule ./cramers_rule.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/cramers_rule .
CMD ["./cramers_rule"]
