# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./cantor_set.c .
RUN gcc -O3 -o ./cantor_set ./cantor_set.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/cantor_set .
CMD ["./cantor_set"]
