# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./combinations_with_repetitions.c .
RUN gcc -O3 -o ./combinations_with_repetitions ./combinations_with_repetitions.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/combinations_with_repetitions .
CMD ["./combinations_with_repetitions"]
