# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./ray-casting_algorithm.c .
RUN gcc -O3 -o ./ray-casting_algorithm ./ray-casting_algorithm.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/ray-casting_algorithm .
CMD ["./ray-casting_algorithm"]
