# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache clang gfortran make musl-dev
WORKDIR /app
COPY . .
RUN gcc -O3 -I utilities -I medley/floyd-warshall utilities/polybench.c medley/floyd-warshall/floyd-warshall.c -DPOLYBENCH_TIME -o medley/floyd-warshall/floyd-warshall -lm
RUN cp medley/floyd-warshall/floyd-warshall /app

# Production stage
FROM alpine
COPY --from=build-stage /app/floyd-warshall /floyd-warshall
CMD ["/floyd-warshall"]
