# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./huffman_coding.c .
RUN gcc -O3 -o ./huffman_coding ./huffman_coding.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/huffman_coding .
CMD ["./huffman_coding"]
