# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./dinesmans_multiple-dwelling_problem.c .
RUN gcc -O3 -o ./dinesmans_multiple-dwelling_problem ./dinesmans_multiple-dwelling_problem.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/dinesmans_multiple-dwelling_problem .
CMD ["./dinesmans_multiple-dwelling_problem"]
