# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./string_concatenation.c .
RUN gcc -O3 -o ./string_concatenation ./string_concatenation.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/string_concatenation .
CMD ["./string_concatenation"]
