# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./random_numbers.c .
RUN gcc -O3 -o ./random_numbers ./random_numbers.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/random_numbers .
CMD ["./random_numbers"]
