# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache clang gfortran make musl-dev
WORKDIR /app
COPY . .
RUN gcc -O3 -I utilities -I linear-algebra/blas/trmm utilities/polybench.c linear-algebra/blas/trmm/trmm.c -DPOLYBENCH_TIME -o linear-algebra/blas/trmm/trmm -lm
RUN cp linear-algebra/blas/trmm/trmm /app

# Production stage
FROM alpine
COPY --from=build-stage /app/trmm /trmm
CMD ["/trmm"]
