# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./anti-primes.c .
RUN gcc -O3 -o ./anti-primes ./anti-primes.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/anti-primes .
CMD ["./anti-primes"]
