# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./weird_numbers.c .
RUN gcc -O3 -o ./weird_numbers ./weird_numbers.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/weird_numbers .
CMD ["./weird_numbers"]
