# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./integer_overflow.c .
RUN gcc -O3 -o ./integer_overflow ./integer_overflow.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/integer_overflow .
CMD ["./integer_overflow"]
