# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./csv_to_html_translation.c .
RUN gcc -O3 -o ./csv_to_html_translation ./csv_to_html_translation.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/csv_to_html_translation .
CMD ["./csv_to_html_translation"]
