# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./range_expansion.c .
RUN gcc -O3 -o ./range_expansion ./range_expansion.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/range_expansion .
CMD ["./range_expansion"]
