# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./stable_marriage_problem.c .
RUN gcc -O3 -o ./stable_marriage_problem ./stable_marriage_problem.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/stable_marriage_problem .
CMD ["./stable_marriage_problem"]
