# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./move-to-front_algorithm.c .
RUN gcc -O3 -o ./move-to-front_algorithm ./move-to-front_algorithm.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/move-to-front_algorithm .
CMD ["./move-to-front_algorithm"]
