# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache clang gfortran make musl-dev
WORKDIR /app
COPY . .
RUN gcc -O3 -I utilities -I stencils/heat-3d utilities/polybench.c stencils/heat-3d/heat-3d.c -DPOLYBENCH_TIME -o stencils/heat-3d/heat-3d -lm
RUN cp stencils/heat-3d/heat-3d /app

# Production stage
FROM alpine
COPY --from=build-stage /app/heat-3d /heat-3d
CMD ["/heat-3d"]
