# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./water_collected_between_towers.c .
RUN gcc -O3 -o ./water_collected_between_towers ./water_collected_between_towers.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/water_collected_between_towers .
CMD ["./water_collected_between_towers"]
