# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./linear_congruential_generator.c .
RUN gcc -O3 -o ./linear_congruential_generator ./linear_congruential_generator.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/linear_congruential_generator .
CMD ["./linear_congruential_generator"]
