# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./determine_if_a_string_has_all_unique_characters.c .
RUN gcc -O3 -o ./determine_if_a_string_has_all_unique_characters ./determine_if_a_string_has_all_unique_characters.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/determine_if_a_string_has_all_unique_characters .
CMD ["./determine_if_a_string_has_all_unique_characters"]
