# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./hash_from_two_arrays.c .
RUN gcc -O3 -o ./hash_from_two_arrays ./hash_from_two_arrays.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/hash_from_two_arrays .
CMD ["./hash_from_two_arrays"]
