# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./convex_hull.c .
RUN gcc -O3 -o ./convex_hull ./convex_hull.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/convex_hull .
CMD ["./convex_hull"]
