# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./forward_difference.c .
RUN gcc -O3 -o ./forward_difference ./forward_difference.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/forward_difference .
CMD ["./forward_difference"]
