# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./faulhabers_formula.c .
RUN gcc -O3 -o ./faulhabers_formula ./faulhabers_formula.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/faulhabers_formula .
CMD ["./faulhabers_formula"]
