# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./fibonacci_n-step_number_sequences.c .
RUN gcc -O3 -o ./fibonacci_n-step_number_sequences ./fibonacci_n-step_number_sequences.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/fibonacci_n-step_number_sequences .
CMD ["./fibonacci_n-step_number_sequences"]
