# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./literals-integer.c .
RUN gcc -O3 -o ./literals-integer ./literals-integer.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/literals-integer .
CMD ["./literals-integer"]
