# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache clang gfortran make musl-dev
WORKDIR /app
COPY . .
RUN gcc -O3 -I utilities -I stencils/jacobi-2d utilities/polybench.c stencils/jacobi-2d/jacobi-2d.c -DPOLYBENCH_TIME -o stencils/jacobi-2d/jacobi-2d -lm
RUN cp stencils/jacobi-2d/jacobi-2d /app

# Production stage
FROM alpine
COPY --from=build-stage /app/jacobi-2d /jacobi-2d
CMD ["/jacobi-2d"]
