# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./binary_digits.c .
RUN gcc -O3 -o ./binary_digits ./binary_digits.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/binary_digits .
CMD ["./binary_digits"]
