# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./cartesian_product_of_two_or_more_lists.c .
RUN gcc -O3 -o ./cartesian_product_of_two_or_more_lists ./cartesian_product_of_two_or_more_lists.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/cartesian_product_of_two_or_more_lists .
CMD ["./cartesian_product_of_two_or_more_lists"]
