# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./hamming_numbers.c .
RUN gcc -O3 -o ./hamming_numbers ./hamming_numbers.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/hamming_numbers .
CMD ["./hamming_numbers"]
