# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./sort_an_integer_array.c .
RUN gcc -O3 -o ./sort_an_integer_array ./sort_an_integer_array.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/sort_an_integer_array .
CMD ["./sort_an_integer_array"]
