# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./reverse_words_in_a_string.c .
RUN gcc -O3 -o ./reverse_words_in_a_string ./reverse_words_in_a_string.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/reverse_words_in_a_string .
CMD ["./reverse_words_in_a_string"]
