# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./averages-mode.c .
RUN gcc -O3 -o ./averages-mode ./averages-mode.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/averages-mode .
CMD ["./averages-mode"]
