# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./optional_parameters.c .
RUN gcc -O3 -o ./optional_parameters ./optional_parameters.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/optional_parameters .
CMD ["./optional_parameters"]
