# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./vigenere_cipher-cryptanalysis.c .
RUN gcc -O3 -o ./vigenere_cipher-cryptanalysis ./vigenere_cipher-cryptanalysis.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/vigenere_cipher-cryptanalysis .
CMD ["./vigenere_cipher-cryptanalysis"]
