# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache clang gfortran make musl-dev
WORKDIR /app
COPY . .
RUN gcc -O3 -I utilities -I linear-algebra/kernels/doitgen utilities/polybench.c linear-algebra/kernels/doitgen/doitgen.c -DPOLYBENCH_TIME -o linear-algebra/kernels/doitgen/doitgen -lm
RUN cp linear-algebra/kernels/doitgen/doitgen /app

# Production stage
FROM alpine
COPY --from=build-stage /app/doitgen /doitgen
CMD ["/doitgen"]
