# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./temperature_conversion.c .
RUN gcc -O3 -o ./temperature_conversion ./temperature_conversion.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/temperature_conversion .
CMD ["./temperature_conversion"]
