# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./day_of_the_week.c .
RUN gcc -O3 -o ./day_of_the_week ./day_of_the_week.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/day_of_the_week .
CMD ["./day_of_the_week"]
