# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./towers_of_hanoi.c .
RUN gcc -O3 -o ./towers_of_hanoi ./towers_of_hanoi.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/towers_of_hanoi .
CMD ["./towers_of_hanoi"]
