# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./sum_of_squares.c .
RUN gcc -O3 -o ./sum_of_squares ./sum_of_squares.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/sum_of_squares .
CMD ["./sum_of_squares"]
