# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./list_comprehensions.c .
RUN gcc -O3 -o ./list_comprehensions ./list_comprehensions.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/list_comprehensions .
CMD ["./list_comprehensions"]
