# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./formal_power_series.c .
RUN gcc -O3 -o ./formal_power_series ./formal_power_series.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/formal_power_series .
CMD ["./formal_power_series"]
