# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./sort_using_a_custom_comparator.c .
RUN gcc -O3 -o ./sort_using_a_custom_comparator ./sort_using_a_custom_comparator.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/sort_using_a_custom_comparator .
CMD ["./sort_using_a_custom_comparator"]
