# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./strip_control_codes_and_extended_characters_from_a_string.c .
RUN gcc -O3 -o ./strip_control_codes_and_extended_characters_from_a_string ./strip_control_codes_and_extended_characters_from_a_string.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/strip_control_codes_and_extended_characters_from_a_string .
CMD ["./strip_control_codes_and_extended_characters_from_a_string"]
