# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./caesar_cipher.c .
RUN gcc -O3 -o ./caesar_cipher ./caesar_cipher.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/caesar_cipher .
CMD ["./caesar_cipher"]
