# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./return_multiple_values.c .
RUN gcc -O3 -o ./return_multiple_values ./return_multiple_values.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/return_multiple_values .
CMD ["./return_multiple_values"]
