# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache clang gfortran make musl-dev
WORKDIR /app
COPY . .
RUN gcc -O3 -I utilities -I linear-algebra/kernels/mvt utilities/polybench.c linear-algebra/kernels/mvt/mvt.c -DPOLYBENCH_TIME -o linear-algebra/kernels/mvt/mvt -lm
RUN cp linear-algebra/kernels/mvt/mvt /app

# Production stage
FROM alpine
COPY --from=build-stage /app/mvt /mvt
CMD ["/mvt"]
