# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./set_consolidation.c .
RUN gcc -O3 -o ./set_consolidation ./set_consolidation.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/set_consolidation .
CMD ["./set_consolidation"]
