# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./attractive_numbers.c .
RUN gcc -O3 -o ./attractive_numbers ./attractive_numbers.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/attractive_numbers .
CMD ["./attractive_numbers"]
