# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./zero_to_the_zero_power.c .
RUN gcc -O3 -o ./zero_to_the_zero_power ./zero_to_the_zero_power.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/zero_to_the_zero_power .
CMD ["./zero_to_the_zero_power"]
