# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./four_bit_adder.c .
RUN gcc -O3 -o ./four_bit_adder ./four_bit_adder.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/four_bit_adder .
CMD ["./four_bit_adder"]
