# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache clang gfortran make musl-dev
WORKDIR /app
COPY . .
RUN gcc -O3 -I utilities -I linear-algebra/solvers/durbin utilities/polybench.c linear-algebra/solvers/durbin/durbin.c -DPOLYBENCH_TIME -o linear-algebra/solvers/durbin/durbin -lm
RUN cp linear-algebra/solvers/durbin/durbin /app

# Production stage
FROM alpine
COPY --from=build-stage /app/durbin /durbin
CMD ["/durbin"]
