# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./sum_data_type.c .
RUN gcc -O3 -o ./sum_data_type ./sum_data_type.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/sum_data_type .
CMD ["./sum_data_type"]
