# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./list_rooted_trees.c .
RUN gcc -O3 -o ./list_rooted_trees ./list_rooted_trees.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/list_rooted_trees .
CMD ["./list_rooted_trees"]
