# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./peaceful_chess_queen_armies.c .
RUN gcc -O3 -o ./peaceful_chess_queen_armies ./peaceful_chess_queen_armies.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/peaceful_chess_queen_armies .
CMD ["./peaceful_chess_queen_armies"]
