# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./split_a_character_string_based_on_change_of_character.c .
RUN gcc -O3 -o ./split_a_character_string_based_on_change_of_character ./split_a_character_string_based_on_change_of_character.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/split_a_character_string_based_on_change_of_character .
CMD ["./split_a_character_string_based_on_change_of_character"]
