# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./thieles_interpolation_formula.c .
RUN gcc -O3 -o ./thieles_interpolation_formula ./thieles_interpolation_formula.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/thieles_interpolation_formula .
CMD ["./thieles_interpolation_formula"]
