# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./polymorphic_copy.c .
RUN gcc -O3 -o ./polymorphic_copy ./polymorphic_copy.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/polymorphic_copy .
CMD ["./polymorphic_copy"]
