# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache clang gfortran make musl-dev
WORKDIR /app
COPY . .
RUN gcc -O3 -I utilities -I linear-algebra/blas/gemver utilities/polybench.c linear-algebra/blas/gemver/gemver.c -DPOLYBENCH_TIME -o linear-algebra/blas/gemver/gemver -lm
RUN cp linear-algebra/blas/gemver/gemver /app

# Production stage
FROM alpine
COPY --from=build-stage /app/gemver /gemver
CMD ["/gemver"]
