# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./sum_multiples_of_3_and_5.c .
RUN gcc -O3 -o ./sum_multiples_of_3_and_5 ./sum_multiples_of_3_and_5.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/sum_multiples_of_3_and_5 .
CMD ["./sum_multiples_of_3_and_5"]
