# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./convert_decimal_number_to_rational.c .
RUN gcc -O3 -o ./convert_decimal_number_to_rational ./convert_decimal_number_to_rational.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/convert_decimal_number_to_rational .
CMD ["./convert_decimal_number_to_rational"]
