# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./undefined_values.c .
RUN gcc -O3 -o ./undefined_values ./undefined_values.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/undefined_values .
CMD ["./undefined_values"]
