# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./deal_cards_for_freecell.c .
RUN gcc -O3 -o ./deal_cards_for_freecell ./deal_cards_for_freecell.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/deal_cards_for_freecell .
CMD ["./deal_cards_for_freecell"]
