# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./terminal_control-ringing_the_terminal_bell.c .
RUN gcc -O3 -o ./terminal_control-ringing_the_terminal_bell ./terminal_control-ringing_the_terminal_bell.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/terminal_control-ringing_the_terminal_bell .
CMD ["./terminal_control-ringing_the_terminal_bell"]
