# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./elementary_cellular_automaton-random_number_generator.c .
RUN gcc -O3 -o ./elementary_cellular_automaton-random_number_generator ./elementary_cellular_automaton-random_number_generator.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/elementary_cellular_automaton-random_number_generator .
CMD ["./elementary_cellular_automaton-random_number_generator"]
