# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./y_combinator.c .
RUN gcc -O3 -o ./y_combinator ./y_combinator.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/y_combinator .
CMD ["./y_combinator"]
