# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./chinese_remainder_theorem.c .
RUN gcc -O3 -o ./chinese_remainder_theorem ./chinese_remainder_theorem.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/chinese_remainder_theorem .
CMD ["./chinese_remainder_theorem"]
