# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./copy_a_string.c .
RUN gcc -O3 -o ./copy_a_string ./copy_a_string.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/copy_a_string .
CMD ["./copy_a_string"]
