# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./topological_sort.c .
RUN gcc -O3 -o ./topological_sort ./topological_sort.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/topological_sort .
CMD ["./topological_sort"]
