# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache clang gfortran make musl-dev
WORKDIR /app
COPY . .
RUN gcc -O3 -I utilities -I medley/deriche utilities/polybench.c medley/deriche/deriche.c -DPOLYBENCH_TIME -o medley/deriche/deriche -lm
RUN cp medley/deriche/deriche /app

# Production stage
FROM alpine
COPY --from=build-stage /app/deriche /deriche
CMD ["/deriche"]
