# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./levenshtein_distance-alignment.c .
RUN gcc -O3 -o ./levenshtein_distance-alignment ./levenshtein_distance-alignment.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/levenshtein_distance-alignment .
CMD ["./levenshtein_distance-alignment"]
