# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./string_prepend.c .
RUN gcc -O3 -o ./string_prepend ./string_prepend.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/string_prepend .
CMD ["./string_prepend"]
