# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./sexy_primes.c .
RUN gcc -O3 -o ./sexy_primes ./sexy_primes.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/sexy_primes .
CMD ["./sexy_primes"]
