# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./run-length_encoding.c .
RUN gcc -O3 -o ./run-length_encoding ./run-length_encoding.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/run-length_encoding .
CMD ["./run-length_encoding"]
