# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./long_multiplication.c .
RUN gcc -O3 -o ./long_multiplication ./long_multiplication.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/long_multiplication .
CMD ["./long_multiplication"]
