# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache clang gfortran make musl-dev
WORKDIR /app
COPY . .
RUN COMPILE
RUN cp RESULT /app

# Production stage
FROM alpine
COPY --from=build-stage /app/FNAME /FNAME
CMD ["/FNAME"]
