# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./unicode_strings.c .
RUN gcc -O3 -o ./unicode_strings ./unicode_strings.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/unicode_strings .
CMD ["./unicode_strings"]
