# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./modular_arithmetic.c .
RUN gcc -O3 -o ./modular_arithmetic ./modular_arithmetic.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/modular_arithmetic .
CMD ["./modular_arithmetic"]
