# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./mcnuggets_problem.c .
RUN gcc -O3 -o ./mcnuggets_problem ./mcnuggets_problem.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/mcnuggets_problem .
CMD ["./mcnuggets_problem"]
