# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./bell_numbers.c .
RUN gcc -O3 -o ./bell_numbers ./bell_numbers.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/bell_numbers .
CMD ["./bell_numbers"]
