# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./loops-n_plus_one_half.c .
RUN gcc -O3 -o ./loops-n_plus_one_half ./loops-n_plus_one_half.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/loops-n_plus_one_half .
CMD ["./loops-n_plus_one_half"]
