# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./best_shuffle.c .
RUN gcc -O3 -o ./best_shuffle ./best_shuffle.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/best_shuffle .
CMD ["./best_shuffle"]
