# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./feigenbaum_constant_calculation.c .
RUN gcc -O3 -o ./feigenbaum_constant_calculation ./feigenbaum_constant_calculation.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/feigenbaum_constant_calculation .
CMD ["./feigenbaum_constant_calculation"]
