# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./van_eck_sequence.c .
RUN gcc -O3 -o ./van_eck_sequence ./van_eck_sequence.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/van_eck_sequence .
CMD ["./van_eck_sequence"]
