# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./s-expressions.c .
RUN gcc -O3 -o ./s-expressions ./s-expressions.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/s-expressions .
CMD ["./s-expressions"]
