# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./welchs_t-test.c .
RUN gcc -O3 -o ./welchs_t-test ./welchs_t-test.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/welchs_t-test .
CMD ["./welchs_t-test"]
