# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./ternary_logic.c .
RUN gcc -O3 -o ./ternary_logic ./ternary_logic.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/ternary_logic .
CMD ["./ternary_logic"]
