# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./averages-pythagorean_means.c .
RUN gcc -O3 -o ./averages-pythagorean_means ./averages-pythagorean_means.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/averages-pythagorean_means .
CMD ["./averages-pythagorean_means"]
