# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./numeric_error_propagation.c .
RUN gcc -O3 -o ./numeric_error_propagation ./numeric_error_propagation.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/numeric_error_propagation .
CMD ["./numeric_error_propagation"]
