# Build stage
FROM alpine AS build-stage
RUN apk add --no-cache gcc gfortran make musl-dev g++
WORKDIR /app
COPY ./kahan_summation.c .
RUN gcc -O3 -o ./kahan_summation ./kahan_summation.c -lm
# RUN cp RESULT /app

# Production stage
FROM alpine
# RUN apk add --no-cache libc-dev
COPY --from=build-stage /app/kahan_summation .
CMD ["./kahan_summation"]
